# Master parameter list

# SLAM
hector_mapping:
	pub_map_odom_transform: true
	use_tf_scan_transformation: true
	map_frame: map
	base_frame: base_link_bottom
	odom_frame: base_link_bottom

	map_resolution: 0.1
	map_size: 1024
	map_start_x: 0.5
	map_start_y: 0.5
	map_multi_res_levels: 2

	update_factor_free: 0.4
	update_factor_occupied: 0.9
	map_update_distance_thresh: 0.4
	map_update_angle_thresh: 0.06
	laser_z_min_value: -0.1
	laser_z_max_value: 1.0

	advertise_map_service: true
	scan_subscriber_queue_service: 0.05
	scan_topic: scan

hector_trajectory_server:
	target_frame_name: /map
	source_frame_name: /base_link_bottom
	trajectory_update_rate: 3
	trajectory_publish_rate: 0.25



# LOCALIZATION
ukf_localization:
  frequency: 30
  sensor_timeout: 0.1
  two_d_mode: false
  transform_time_offset: 0.0
  print_diagnostics: true
  debug: false

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  # world_frame: map

  imu0: imu
  imu0_config: [false, false, false,
                true,  true,  true,
                false, false, false,
                true,  true,  true,
                true,  true,  true]
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: false
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true


  pose0: poseupdate
  pose0_config: [true, true, true,
                true,  true,  true,
                false, false, false,
                false, false, false,
                false, false, false]
  pose0_nodelay: false
  pose0_differential: false
  pose0_relative: false
  pose0_queue_size: 10





#navsat_transform:

#  frequency: 30
#  delay: 0.0
#  magnetic_declination_radians: 0.15708
#  yaw_offset: -90
#  broadcast_utm_transform: false
#  publish_filtered_gps: false
#  use_odometry_yaw: false
#  wait_for_datum: false

